### ISSUE TITLE
AttributeError: '_OpNamespace' object has no attribute 'get_patches_forward'

### ISSUE THREAD

**Issue by LooperzZ** [Shiaoming/ALIKED#18]
INFO:root:Loading 5 images
loading D:\DL_matching\ALIKED-main\models\aliked-n16rot.pth
C:\software\Anaconda3\envs\pytorch_gpu\lib\site-packages\torch\functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:2895.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
INFO:root:Press 'space' to start. 
Press 'q' or 'ESC' to stop!
Traceback (most recent call last):
  File "C:\software\Anaconda3\envs\pytorch_gpu\lib\site-packages\torch\_ops.py", line 198, in __getattr__
    op, overload_names = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator custom_ops::get_patches_forward

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\DL_matching\ALIKED-main\demo_pair.py", line 116, in <module>
    pred_ref = model.run(img_rgb)
  File "D:\DL_matching\ALIKED-main\nets\aliked.py", line 166, in run
    pred = self.forward(img_tensor)
  File "D:\DL_matching\ALIKED-main\nets\aliked.py", line 148, in forward
    descriptors, offsets = self.desc_head(feature_map, keypoints)
  File "C:\software\Anaconda3\envs\pytorch_gpu\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\DL_matching\ALIKED-main\nets\blocks.py", line 227, in forward
    patch = self.get_patches_func(xi, kptsi_wh.long(), self.kernel_size)  # [N_kpts, C, K, K]
  File "D:\DL_matching\ALIKED-main\custom_ops\__init__.py", line 18, in forward
    patches = torch.ops.custom_ops.get_patches_forward(fmap, points, kernel_size)
  File "C:\software\Anaconda3\envs\pytorch_gpu\lib\site-packages\torch\_ops.py", line 202, in __getattr__
    raise AttributeError(f"'_OpNamespace' object has no attribute '{op_name}'") from e
AttributeError: '_OpNamespace' object has no attribute 'get_patches_forward'

**Comment by Magico23** [comment]
I'm having the same problem,  have you solved it now

**Comment by NemB0t** [comment]
I had the same problem. I faced the issue because I had not built the custom ops as mentioned by the author. Once I build it it got fixed.
